version: 2.1
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: docker:19.03-rc # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: "Container Build"
          command: "docker-compose build"
      - run:
          name: "Container Up"
          command: "docker-compose up -d"
      - run:
          name: "run test"
          command: "docker exec easy-api-mocker npm run test"